data:
    provider:
        url: http://localhost:8090/api/v1
findwork:
    token: 2a63f298d63f2cda7b33df3b6a2741aeca96d9aa
    url: https://findwork.dev/api

job:
    platforms: findWork
logging:
    config: logback.xml
server:
    error:
        include-message: always
spring:
    datasource:
        password: root
        url: jdbc:postgresql://localhost:5432/reference
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
